name: Build and test
on:
  push:

jobs:
  build-and-test:
    name: Build and test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        if: false
        working-directory: ${{ github.workspace }}
        run: msbuild -m -p:Configuration=Release -p:Platform=x64 Nand2Tetris.sln

      - name: Tests
        shell: cmd
        run: |
          cmd /c "RunTests.bat ${{ github.workspace }}"
